name: '[Manual] Deploy Lambda Function'

on:
  workflow_dispatch:

env:
  REST_API_ID: ${{ vars.REST_API_ID }}
  REST_API_ROOT_RESOURCE_ID: ${{ vars.REST_API_ROOT_RESOURCE_ID }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Dependencies
        run: |
          npm i
          npm i -g serverless
          pip install -r requirements.txt
      
      - name: Serverless Deploy
        run: |
          npm run sls:deploy:prd
